### ISSUE TITLE
Sega CD save states not properly restored

### ISSUE THREAD

**Issue by rik-smeets** [irixxxx/picodrive#57] opened 2022-01-03 10:22 UTC
Software: PicoDrive version 1.99, compiled for MiyooCFW
Hardware: PowKiddy V90

In SEGA CD games, save states don't seem to work properly. Saving a state always succeeds, but loading a previously saved state fails in multiple ways. Some examples:

- In The Terminator, loading a save state whilst in the same game session works perfectly. However, if you restart the emulator and therefore start a new game session, loading the save state does not work properly. The music plays, but the screen is frozen and no input works.
- In the Lunar games, loading a save state also doesn't work within the same game session. Whenever a new area needs to load, a black screen is displayed and it does not progress any further. Other glitches occur as well: after loading the state, the music plays in a short loop instead of the entire track playing.

I have not found a workaround yet, hope there is one to be found.

**Comment by DrUm78** [comment] 2022-01-03 11:21
The Terminator works fine for me. Have you compiled the latest code (there was a savestate fix in https://github.com/irixxxx/picodrive/commit/fda7339b94e33bed3fee4f48bc5286f27f9eb19b)?

**Comment by rik-smeets** [comment] 2022-01-03 12:10
No, I am using the latest release binaries (1.99). 

I don't know how to compile the latest code to something I can use with MiyooCFW, I don't even understand the README for the other target platforms 😅. My programming experience is mostly limited to .NET on Windows environments. If you could guide me in the right direction I'd appreciate it, would love to test if the problem was resolved with that commit.

**Comment by irixxxx** [comment] 2022-01-03 13:26
There were some changes to save/load after the 1.99 release. However I don't provide miyoo binaries myself, since I don't have the hardware and I usually only provide binaries onle if I have hardware or a reasonably good working emulator. @freq-mod is the one supplying miyoo binaries. Could you please make contact and ask for a binary from the current sources?

**Comment by freq-mod** [comment] 2022-01-03 13:40
@rik-smeets  fresh miyoo binary, please test
[PicoDrive.zip](https://github.com/irixxxx/picodrive/files/7802174/PicoDrive.zip)

**Comment by rik-smeets** [comment] 2022-01-03 14:45
Thanks for the new build, @freq-mod!

I just performed some tests. The issue is not (fully) resolved, but I did find a workaround. Not sure if that worked before as well, as I didn't think of this earlier.

**Repro steps:**
- Play 'The Terminator' up until the second level. Save a state.
- Close the emulator and restart the game. Load the previously saved state. 

On my device, this results in a frozen screen with just the music playing.

**Workaround:**
When you start the game, save a new state in another slot. You can even make the save state on the SEGA CD opening screen; it really doesn't matter. Now, load the save state where you're in level 2. It now works!
It's as if the action of saving a state fixes something that's missing when restoring the state?

**Comment by Apaczer** [comment] 2022-01-03 20:10
Hi,

The savestate functionality was broken in MD-CD since the 1.93 had been ported for Miyoo devices. To reproduce that issue you need simply to use savestate 2-times (at least from my exp. in that game), then all following states will be "corrupted" after rebooting emu.

Yup, creating "dummy" savestate at the beginning and then loading it seems to revert all coruption.

**Comment by DrUm78** [comment] 2022-01-03 20:56
Indeed, seems to be a Miyoo only issue, I cannot reproduce it on the FunKey S.

**Comment by irixxxx** [comment] 2022-01-03 22:40
Hmm no, there's more in it, I think. I improved vdp state handling a bit. I suspect this is somehow connected. @freq-mod could you please supply a new test binary for @rik-smeets?

**Comment by freq-mod** [comment] 2022-01-03 22:44
I will take a look at it tomorrow.

**Comment by freq-mod** [comment] 2022-01-04 12:17
[PicoDrive.zip](https://github.com/irixxxx/picodrive/files/7807484/PicoDrive.zip) fresh master miyoo build, sorry for keeping you waiting so long

**Comment by rik-smeets** [comment] 2022-01-04 15:29
No need to say sorry @freq-mod, I appreciate your time and it's still very fast!

Unfortunately the issue seems to be unresolved. I still need to use the workaround, otherwise, the exact same problem occurs.

**Comment by irixxxx** [comment] 2022-01-04 16:47
since this  helps with mcd in libretro save/load, would you please apply this small patch?
[y.txt](https://github.com/irixxxx/picodrive/files/7809067/y.txt)

**Comment by freq-mod** [comment] 2022-01-04 17:31
[PicoDrive.zip](https://github.com/irixxxx/picodrive/files/7809333/PicoDrive.zip)

**Comment by rik-smeets** [comment] 2022-01-04 18:02
Looks like the issue's been resolved! With my old save states, the same problem would still occur. However, I figured those states themselves might be incomplete/incorrect. So I tried recreating some new states in different levels and loading them works fine every time! Thanks so much!

**Comment by Apaczer** [comment] 2022-01-04 19:56
@rik-smeets could you check again? The issue still persist with applied patch from my end (on V90).

**Comment by irixxxx** [comment] 2022-01-04 21:21
Thx @freq-mod for helping out!

**Comment by rik-smeets** [comment] 2022-01-05 18:49
Unfortunately, @Apaczer is right. The issue also still persists on my end. His analysis seems to be correct too. I thought it had something to do with changing levels/areas, but that doesn't look like it anymore. Any save after some amount of time after the first save does indeed seem to corrupt.

**Comment by irixxxx** [comment] 2022-01-06 21:42
I've changed several things in save state stuff. @freq-mod could you possibly make another binary please?

**Comment by freq-mod** [comment] 2022-01-07 17:18
[PicoDrive.zip](https://github.com/irixxxx/picodrive/files/7830281/PicoDrive.zip) please try

**Comment by rik-smeets** [comment] 2022-01-07 18:34
Can confirm the issue isn't resolved yet. It does seem to happen a little less often, but since I don't know exactly when the issue occurs, it's hard to tell.

**Comment by irixxxx** [comment] 2022-01-07 20:02
Please describe exactly what you are doing. I'm absolutely fishing in the dark as long as I can't reproduce this. Which I can't up to now... everything I did solved some save/load problem elsewhere.

**Comment by Apaczer** [comment] 2022-01-07 21:42
To reproduce on Miyoo's devices:
- Play MD-CD game at least for 5min approx..
- Make at least 2 save states

Result:
- second on onwards s.states become corrupted

**Comment by irixxxx** [comment] 2022-01-07 22:10
Is this by any chance happening after exactly 3 minutes? That's when the cycle counter for the sub cpu overflows.

**Comment by Apaczer** [comment] 2022-01-09 21:06
The 6 min seems sufficent albeit I did not manage to reproduce that bug without turning OFF and ON mentioned console. Please have in mind that Miyoo devices do not have internal clock and every restart will revert time to stock value. I don't know how time stamps might affect this but here they are all over the place (due to lack of mentioned feature).

**Comment by Apaczer** [comment] 2022-01-09 22:17
I've triple checked and setting correct time in V90's system settings before booting emulator indeed fix the issue. Sorry if we might have mislead in that matter.

**Comment by Apaczer** [comment] 2022-01-09 23:18
So the steps to reproduce on others devices with working hardware's clock would be (please check):
- Boot/reset device
- Set improper time (earlier than current saves eg. 2019 year) in device's menu 
- Play MD-CD game at least for 6min
- Make at least 2 save states

Result:
- second and onwards s.states become corrupted

For Miyoo's console see earlier post (EDIT)

**Comment by Apaczer** [comment] 2022-08-07 14:56
This has been fixed externally on latest [GMenu2x](https://github.com/Apaczer/gmenu2x/releases/tag/v20220806) build (at least to some extent) with improved SW clock reading.
Of course issue will still persist on other frontends (e.g. Simplemenu) without accommodating for lack of HW clock on Miyoo devices.

**Comment by DrUm78** [comment] 2022-08-07 18:58
Not sure what the frontend has to do here as it's only a launcher and does not persist in background. 🤔

**Comment by irixxxx** [comment] 2022-08-07 19:23
Well, the save contains the date of the save. I just can't see how setting a date earlier than that can do any harm. It apparently doesn't on Linux, at least I can't reproduce this there.

**Comment by irixxxx** [comment] 2022-08-10 10:05
Could someone please show me the save file overview page after setting a time before some of the saves?

**Comment by anzz1** [comment] 2023-05-11 08:44
Regarding this, I ultimately found the Cyclone68K core to be the culprit. As noted in my lengthy post in #85 earlier, I had problems trying to implement the C68K core for use in CPS and NeoGeo emulation, using fbalpha as the base. I thought that the messy codebase of fbalpha was to blame, but it now seems that it wasn't the case after all, as exactly the same savestate issues surfaced here too, mainly in regards to "autoresuming" (launch libretro with the option to resume a savestate right from the start) resulting in segfaulting. 

This time I first thought it was the paltry 128MB of ram on miyoomini to be the cause, but after using a swapfile didn't help I dug in more. Using the Fame (F68K, C) cpu instead of the Cyclone (C68K, arm-asm) one solved all the issues. It also seems that the arm-gnueabihf gcc 8.3.0 with the right compiler flags produces pretty good code even with the C core, as the performance difference between the two was negligible in this case.

Here is the compiled binary in case you're interested in output, with the exact configuration from [this commit](https://github.com/anzz1/picoarch/commit/964cfb8aedd46cb3f4074975fea24c66002366b5f).
[picodrive_libretro.zip](https://github.com/irixxxx/picodrive/files/11449900/picodrive_libretro.zip)

I'm also open to helping with debugging if you give me instructions what to do, as I don't really know how to approach that on a device with such little RAM. Making a debug build with different compiler flags would change the charasteristics and as such wouldn't help much, and I don't think it's even possible to run a profiling framework like valgrind on this. So I don't know how to find out exactly *where* it crashes and *why*.

---

There is also some problems with the current makefile configuration. Looking through the logic and the steps Makefile.libretro -> include Makefile -> include common.mak , everything seems correct but in reality, at least on my case, some of the compiler flags and defines get lost along the way. Using the `export` definition in makefile might work, but it should be only needed for passing `MAKEFLAGS` to another make process, and when `include`'ing it shouldn't be needed and simply be as-if the different parts are all a part of the same file, however this doesn't seem to happen in reality, make being the buggy mess what it is.

The loosing of some critical defines lead to issues where some of the defines were defined but also not defined, and it ended up building two codepaths with `HAVE_ARM` and without, when same sources were included in different compilation units which is definitely a bad thing. The way I tested this was by adding a `#error Stop` directive in either side of the `#else` in various parts , like in here https://github.com/irixxxx/picodrive/blob/master/cpu/drc/emit_arm.c#L481 and here https://github.com/notaz/cyclone68000/blob/425e3a4066ee1cc8a3bae28956fbbdc9a516001d/OpAny.cpp#L182 . The compilation stopped at the `#error` whether it was on either side of the `#else`, but from different sources.

Also there are versions in the ARM flags with both upper-case V and lower-case v, `HAVE_ARMV6` / `HAVE_ARMv6` , which aren't the same from the compiler's perspective as the definitions are case-sensitive. 

Many conditionals in `common.mak` don't seem to work at all, the defines like `_ASM_DRAW_C` aren't getting defined and the sources added even when defining `asm_render=1`. However later down the `use_fame`, `use_cyclone`, etc were, but the defines were defined only for some of the compilation units. At one point it even built all the different cores at the same time for some unknown reason.

In any case, this is the patch which ultimately made everything work: https://github.com/anzz1/picoarch/commit/964cfb8aedd46cb3f4074975fea24c66002366b5#diff-0c0fb0aab810c381cdd64cbca6a6464d98869da0ecc7ed7168ca80495875567f
Maybe it looks a bit ridiculous but it works. I explicitly defined everything , for everything , and now nothing is lost and the configuration needed gets built correctly.

Having had more headaches than I can count with different make scripts I've always come to the same solution, which is to keep it simple. Having everything in a single Makefile with all the required flags in one place, without any automatic configuration trying to be smart nor defining anything in the sources (like is being done with "arm_features.h", which probably is the reason for the two-codepath issue mentioned above) is the way to go, trying anything fancy with compiler flags or defines is just asking for trouble.

I know cleaning up and consolidating the makefile is a chore which isn't fun to do at all, but it should be considered to have in the backlog at least to be done at some point. The simple logic which many cores use that there is a single "Makefile" for the standalone build and a "Makefile.libretro" for the libretro one, without any other extenral parts seems to be the most effective.

**Comment by irixxxx** [comment] 2023-05-11 15:54
> Regarding this, I ultimately found the Cyclone68K core to be the culprit. As noted in my lengthy post in #85 earlier, I had problems trying to implement the C68K core for use in CPS and NeoGeo emulation, using fbalpha as the base. I thought that the messy codebase of fbalpha was to blame, but it now seems that it wasn't the case after all, as exactly the same savestate issues surfaced here too, mainly in regards to "autoresuming" (launch libretro with the option to resume a savestate right from the start) resulting in segfaulting.
> 
> This time I first thought it was the paltry 128MB of ram on miyoomini to be the cause, but after using a swapfile didn't help I dug in more. Using the Fame (F68K, C) cpu instead of the Cyclone (C68K, arm-asm) one solved all the issues. It also seems that the arm-gnueabihf gcc 8.3.0 with the right compiler flags produces pretty good code even with the C core, as the performance difference between the two was negligible in this case.
> 
> Here is the compiled binary in case you're interested in output, with the exact configuration from [this commit](https://github.com/anzz1/picoarch/commit/964cfb8aedd46cb3f4074975fea24c66002366b5f). [picodrive_libretro.zip](https://github.com/irixxxx/picodrive/files/11449900/picodrive_libretro.zip)
> 
> I'm also open to helping with debugging if you give me instructions what to do, as I don't really know how to approach that on a device with such little RAM. Making a debug build with different compiler flags would change the charasteristics and as such wouldn't help much, and I don't think it's even possible to run a profiling framework like valgrind on this. So I don't know how to find out exactly _where_ it crashes and _why_.

The Cyclone emulator must be initialized once by calling ``CycloneReset()`` somewhere, which is normally done be the BIOS, but not for autoloads. Adding a ``SekResetS68k()`` in ``PicoResetMCD`` fixes this, I think. I'll check this later, but for testing purposes you might just want to add that call and see if it works for you.

> There is also some problems with the current makefile configuration. Looking through the logic and the steps Makefile.libretro -> include Makefile -> include common.mak , everything seems correct but in reality, at least on my case, some of the compiler flags and defines get lost along the way. Using the `export` definition in makefile might work, but it should be only needed for passing `MAKEFLAGS` to another make process, and when `include`'ing it shouldn't be needed and simply be as-if the different parts are all a part of the same file, however this doesn't seem to happen in reality, make being the buggy mess what it is.
> [...]
> Having had more headaches than I can count with different make scripts I've always come to the same solution, which is to keep it simple. Having everything in a single Makefile with all the required flags in one place, without any automatic configuration trying to be smart nor defining anything in the sources (like is being done with "arm_features.h", which probably is the reason for the two-codepath issue mentioned above) is the way to go, trying anything fancy with compiler flags or defines is just asking for trouble.

That Makefile structure probably stems from the origins of Picodrive, and nobody (including me) ever bothered enough to change this. It's a catastrophe in several respects, just look at the completely broken dependencies in there. The configure stuff is also very stone age... it's however a lot of work to get this right, especially considering that I'm neither an autoconf nor a make buff.

**Comment by irixxxx** [comment] 2023-11-27 17:04
Closing this as I have no proof this is still happening. If anyone still has this happening please reopen tight away!

**Closed by irixxxx** 2023-11-27 17:04 UTC
