### ISSUE TITLE
Savestates don't work right in RetroArch port for Wii U

### ISSUE THREAD

**Issue by KnightofTime** [irixxxx/picodrive#124] opened 2024-04-06 14:28 UTC
Hi guys,

Lately I re-downloaded RetroArch for my Wii U, and I attempted to play a couple of games in PicoDrive version 1.99 (Knuckles' Chaotix & Mega Man: The Wily Wars), and I noticed savestates are broken here; if you make a savestate and then load it, the game freezes even though the music continues to play.  Can someone please fix this?  PicoDrive savestates did work in a previous version (I can't remember which); I played Knuckles Chaotiix with savestates a few days ago, and they worked fine for that version, so I dunno what version they ended up breaking in.

Thanks in advance.

**Comment by irixxxx** [comment] 2024-04-06 22:01
Should be fixed in 2.00-beta2, which has been recently merge into lr-picodrive. Please check with that Version.

**Comment by irixxxx** [comment] 2024-04-06 22:02
Duplicate of #120

**Closed by irixxxx** 2024-04-06 22:02 UTC
